### ISSUE TITLE
please fix the following error

### ISSUE THREAD

**Issue by GopalKarankar** [MusabDev/php-google-login#1]
Fatal error: Uncaught Error: Class "Google_Client" not found in C:\xampp\htdocs\practice\musadev\config.php:13 Stack trace: #0 C:\xampp\htdocs\practice\musadev\index.php(2): require_once() #1 {main} thrown in C:\xampp\htdocs\practice\musadev\config.php on line 13

**Comment by MusabDev** [comment]
Install packages with `composer install`

**Comment by GopalKarankar** [comment]
thanx
